"""
Integration tests for the feature data streaming endpoint.

Endpoint under test:
  GET /domains/{domain_id}/features/{feature_id}/data?page=&size=

These tests run against static GeoJSON blobs at
``gs://{FEATURES_BUCKET}/static-test-blue-mtn-osm-{roads,water}.geojson``
generated by ``tests/e2e/test_create_fixtures.py``. The session-scoped
Firestore fixtures copy each static blob into the test domain so the API's
domain-prefixed blob resolver finds it.

Cache-dependent error cases (missing blob, malformed GeoJSON, oversize page)
use ``monkeypatch`` to swap the cache function on the router module — the
same pattern grids/inventories use to avoid flushing the ``ring.lru``
storage between tests.
"""

import json
from types import SimpleNamespace
from uuid import uuid4

import gcsfs
import pytest
from api.resources.features import cache as features_cache
from api.resources.features import router as features_router
from api.resources.features.cache import InvalidFeatureGeoJSON, PageTooLarge
from fastapi import HTTPException

from lib.config import FEATURES_BUCKET, FEATURES_COLLECTION
from lib.testing import SHARED_TEST_FEATURES_DIR
from tests.fixtures import make_feature_data

STATIC_ROADS = "static-test-blue-mtn-osm-roads"
STATIC_WATER = "static-test-blue-mtn-osm-water"


# Helpers


def _load_static_template(static_name: str) -> dict:
    path = SHARED_TEST_FEATURES_DIR / f"{static_name}.json"
    if not path.exists():
        pytest.skip(
            f"{path} not found. Run the e2e fixture generator for {static_name}."
        )
    with open(path) as f:
        return json.load(f)


def _load_static_geojson(static_name: str) -> dict:
    """Read the static GeoJSON blob from bucket root for cross-checking."""
    fs = gcsfs.GCSFileSystem()
    url = f"{FEATURES_BUCKET}/{static_name}.geojson"
    if not fs.exists(url):
        pytest.skip(
            f"gs://{url} not found. Run the e2e fixture generator for {static_name}."
        )
    with fs.open(url, "rb") as f:
        return json.loads(f.read())


def data_route(domain_id: str, feature_id: str, **params):
    return f"/domains/{domain_id}/features/{feature_id}/data", params


def _install_static_feature(firestore_client, test_owner_id, domain_id, static_name):
    """Copy the bucket-root static blob into the test domain + register Firestore doc."""
    fs = gcsfs.GCSFileSystem()
    src = f"{FEATURES_BUCKET}/{static_name}.geojson"
    dst = f"{FEATURES_BUCKET}/{domain_id}/{static_name}.geojson"
    if not fs.exists(src):
        pytest.skip(
            f"gs://{src} not found. Run the e2e fixture generator for {static_name}."
        )
    if fs.exists(dst):
        fs.rm(dst)
    fs.cp(src, dst)

    template = _load_static_template(static_name)
    template["id"] = static_name
    template["owner_id"] = test_owner_id
    template["domain_id"] = domain_id
    doc_ref = firestore_client.collection(FEATURES_COLLECTION).document(static_name)
    doc_ref.set(template)
    return template, doc_ref, dst


def _uninstall_static_feature(doc_ref, blob_path):
    fs = gcsfs.GCSFileSystem()
    doc_ref.delete()
    if fs.exists(blob_path):
        fs.rm(blob_path)


# Fixtures


@pytest.fixture(scope="session")
def static_roads_in_firestore(firestore_client, test_owner_id, domain_for_testing):
    template, doc_ref, blob = _install_static_feature(
        firestore_client, test_owner_id, domain_for_testing["id"], STATIC_ROADS
    )
    yield template
    _uninstall_static_feature(doc_ref, blob)


@pytest.fixture(scope="session")
def static_water_in_firestore(firestore_client, test_owner_id, domain_for_testing):
    template, doc_ref, blob = _install_static_feature(
        firestore_client, test_owner_id, domain_for_testing["id"], STATIC_WATER
    )
    yield template
    _uninstall_static_feature(doc_ref, blob)


@pytest.fixture(scope="session")
def static_roads_geojson():
    """The static roads GeoJSON parsed locally for cross-check assertions."""
    return _load_static_geojson(STATIC_ROADS)


@pytest.fixture(scope="session")
def pending_feature_in_firestore(firestore_client, domain_for_testing):
    """A pending feature (not completed) for 404 validation."""
    feat = make_feature_data(
        domain_id=domain_for_testing["id"], name="Pending feature", status="pending"
    )
    doc_ref = firestore_client.collection(FEATURES_COLLECTION).document(feat["id"])
    doc_ref.set(feat)
    yield feat
    doc_ref.delete()


@pytest.fixture(scope="session")
def feature_with_different_owner(firestore_client, domain_with_different_owner):
    feat = make_feature_data(
        domain_id=domain_with_different_owner["id"],
        owner_id="different-owner",
        name="Other user's feature",
        status="completed",
    )
    doc_ref = firestore_client.collection(FEATURES_COLLECTION).document(feat["id"])
    doc_ref.set(feat)
    yield feat
    doc_ref.delete()


@pytest.fixture
def completed_feature_missing_blob(firestore_client, test_owner_id, domain_for_testing):
    """A completed feature whose GCS blob doesn't exist (fresh uuid)."""
    feat = make_feature_data(
        domain_id=domain_for_testing["id"],
        owner_id=test_owner_id,
        name="Missing-blob feature",
        status="completed",
    )
    # Use a definitely-unused uuid so no real blob can exist
    feat["id"] = f"missing-{uuid4().hex}"
    doc_ref = firestore_client.collection(FEATURES_COLLECTION).document(feat["id"])
    doc_ref.set(feat)
    yield feat
    doc_ref.delete()


# Tests


class TestGetFeatureData:
    """Test GET /domains/{domain_id}/features/{feature_id}/data."""

    def test_returns_200_default_page(
        self,
        client,
        domain_for_testing,
        static_roads_in_firestore,
        static_roads_geojson,
    ):
        url, params = data_route(domain_for_testing["id"], STATIC_ROADS)
        response = client.get(url, params=params)
        assert response.status_code == 200, response.text
        assert response.headers["content-type"].startswith("application/geo+json")

        body = response.json()
        assert body["type"] == "FeatureCollection"
        expected_total = len(static_roads_geojson["features"])
        assert len(body["features"]) == expected_total

        assert response.headers["X-Page"] == "0"
        assert response.headers["X-Page-Size"] == "1000"
        assert response.headers["X-Num-Features"] == str(expected_total)
        assert response.headers["X-Total-Features"] == str(expected_total)
        assert response.headers["X-Has-More"] == "false"

    def test_response_body_matches_local_geojson(
        self,
        client,
        domain_for_testing,
        static_roads_in_firestore,
        static_roads_geojson,
    ):
        """Round-trip: concatenated pages reproduce the source feature list in order."""
        size = 2
        page = 0
        collected = []
        seen_total = None
        while True:
            url, params = data_route(
                domain_for_testing["id"], STATIC_ROADS, page=page, size=size
            )
            response = client.get(url, params=params)
            assert response.status_code == 200, response.text
            body = response.json()
            collected.extend(body["features"])
            seen_total = int(response.headers["X-Total-Features"])
            if response.headers["X-Has-More"] == "false":
                break
            page += 1

        assert seen_total == len(static_roads_geojson["features"])
        assert len(collected) == seen_total
        # Order must be preserved (the byte-range splice keeps source order).
        assert [json.dumps(f, sort_keys=True) for f in collected] == [
            json.dumps(f, sort_keys=True) for f in static_roads_geojson["features"]
        ]

    def test_preserves_top_level_crs(
        self,
        client,
        domain_for_testing,
        static_roads_in_firestore,
        static_roads_geojson,
    ):
        """The top-level `crs` block (if present in the source) is preserved
        verbatim in the response body — byte-range splice gives this for free."""
        url, params = data_route(domain_for_testing["id"], STATIC_ROADS, size=2)
        response = client.get(url, params=params)
        assert response.status_code == 200
        body = response.json()
        # OSM roads GeoJSON includes a `crs` block; both source and response
        # should agree (or both should lack one).
        assert body.get("crs") == static_roads_geojson.get("crs")

    def test_water_endpoint_returns_200(
        self, client, domain_for_testing, static_water_in_firestore
    ):
        url, params = data_route(domain_for_testing["id"], STATIC_WATER)
        response = client.get(url, params=params)
        assert response.status_code == 200, response.text
        body = response.json()
        assert body["type"] == "FeatureCollection"
        assert int(response.headers["X-Total-Features"]) == len(body["features"])

    def test_page_out_of_range_returns_422(
        self, client, domain_for_testing, static_roads_in_firestore
    ):
        url, params = data_route(
            domain_for_testing["id"], STATIC_ROADS, page=99999, size=1000
        )
        response = client.get(url, params=params)
        assert response.status_code == 422
        assert "out of range" in response.json()["detail"].lower()

    def test_size_zero_returns_422(
        self, client, domain_for_testing, static_roads_in_firestore
    ):
        url, params = data_route(domain_for_testing["id"], STATIC_ROADS, size=0)
        response = client.get(url, params=params)
        assert response.status_code == 422

    def test_size_too_large_returns_422(
        self, client, domain_for_testing, static_roads_in_firestore
    ):
        url, params = data_route(domain_for_testing["id"], STATIC_ROADS, size=10001)
        response = client.get(url, params=params)
        assert response.status_code == 422

    def test_unknown_feature_returns_404(self, client, domain_for_testing):
        url, params = data_route(
            domain_for_testing["id"], "00000000000000000000000000000000"
        )
        response = client.get(url, params=params)
        assert response.status_code == 404

    def test_feature_owned_by_other_user_returns_404(
        self, client, domain_for_testing, feature_with_different_owner
    ):
        url, params = data_route(
            domain_for_testing["id"], feature_with_different_owner["id"]
        )
        response = client.get(url, params=params)
        assert response.status_code == 404

    def test_pending_feature_returns_422(
        self, client, domain_for_testing, pending_feature_in_firestore
    ):
        """Status mismatch returns 422 — get_document_async raises 422 when the
        actual status differs from the requested document_status="completed"."""
        url, params = data_route(
            domain_for_testing["id"], pending_feature_in_firestore["id"]
        )
        response = client.get(url, params=params)
        assert response.status_code == 422

    def test_completed_feature_with_missing_blob_returns_422(
        self, client, domain_for_testing, completed_feature_missing_blob
    ):
        url, params = data_route(
            domain_for_testing["id"], completed_feature_missing_blob["id"]
        )
        response = client.get(url, params=params)
        assert response.status_code == 422
        assert "not found in storage" in response.json()["detail"].lower()

    @pytest.mark.asyncio
    async def test_malformed_geojson_returns_422(self, monkeypatch):
        """Call the handler directly with a monkeypatched cache that raises
        InvalidFeatureGeoJSON. In-process — the live server isn't involved
        because monkeypatch can't cross process boundaries."""

        async def _ok_doc(*args, **kwargs):
            return None, SimpleNamespace(
                to_dict=lambda: {
                    "id": "feat-x",
                    "domain_id": "dom-1",
                    "status": "completed",
                }
            )

        async def _broken(domain_id, feature_id, page, size):
            raise InvalidFeatureGeoJSON("simulated malformed feature collection")

        monkeypatch.setattr(features_router, "get_document_async", _ok_doc)
        monkeypatch.setattr(features_router, "fetch_feature_page", _broken)

        with pytest.raises(HTTPException) as exc:
            await features_router.get_feature_data(
                request=SimpleNamespace(state=SimpleNamespace(id="owner-1")),
                domain={"id": "dom-1"},
                feature_id="feat-x",
                page=0,
                size=1000,
            )
        assert exc.value.status_code == 422
        assert "malformed" in exc.value.detail.lower()

    @pytest.mark.asyncio
    async def test_413_when_page_exceeds_size_cap(self, monkeypatch):
        """Call the handler directly with a monkeypatched cache that raises
        PageTooLarge — exercises the router's 413 mapping in-process."""

        async def _ok_doc(*args, **kwargs):
            return None, SimpleNamespace(
                to_dict=lambda: {
                    "id": "feat-x",
                    "domain_id": "dom-1",
                    "status": "completed",
                }
            )

        async def _too_large(domain_id, feature_id, page, size):
            raise PageTooLarge(50_000_000, features_cache.MAX_GEOJSON_BYTES)

        monkeypatch.setattr(features_router, "get_document_async", _ok_doc)
        monkeypatch.setattr(features_router, "fetch_feature_page", _too_large)

        with pytest.raises(HTTPException) as exc:
            await features_router.get_feature_data(
                request=SimpleNamespace(state=SimpleNamespace(id="owner-1")),
                domain={"id": "dom-1"},
                feature_id="feat-x",
                page=0,
                size=1000,
            )
        assert exc.value.status_code == 413
        assert "smaller" in exc.value.detail.lower()

    def test_pagination_headers_present_on_every_page(
        self, client, domain_for_testing, static_roads_in_firestore
    ):
        """Every paged response must carry the full X-* header set."""
        url, params = data_route(domain_for_testing["id"], STATIC_ROADS, size=2)
        response = client.get(url, params=params)
        assert response.status_code == 200
        for header in (
            "X-Page",
            "X-Page-Size",
            "X-Num-Features",
            "X-Total-Features",
            "X-Has-More",
        ):
            assert header in response.headers
        # Types: ints stringified; X-Has-More is "true" or "false"
        assert response.headers["X-Page"].isdigit()
        assert response.headers["X-Page-Size"].isdigit()
        assert response.headers["X-Num-Features"].isdigit()
        assert response.headers["X-Total-Features"].isdigit()
        assert response.headers["X-Has-More"] in ("true", "false")
