"""
Integration tests for the feature data streaming endpoints.

Endpoints under test:
  GET /domains/{domain_id}/features/{feature_id}/data/metadata
  GET /domains/{domain_id}/features/{feature_id}/data/{partition_index}

These tests run against static GeoParquet blobs at
``gs://{FEATURES_BUCKET}/static-test-blue-mtn-osm-{roads,water}.parquet``
generated by ``tests/e2e/test_create_fixtures.py``. The session-scoped
Firestore fixtures copy each static blob into the test domain so the
API's domain-prefixed blob resolver finds it.

Cache-dependent error cases (missing blob, malformed Parquet, oversize
partition) use ``monkeypatch`` to swap the cache function on the router
module — the same pattern grids/inventories use to avoid flushing the
``ring.lru`` storage between tests.
"""

import json
from types import SimpleNamespace
from uuid import uuid4

import gcsfs
import geopandas as gpd
import pytest
from api.resources.features import cache as features_cache
from api.resources.features import router as features_router
from api.resources.features.cache import (
    InvalidFeatureParquet,
    PartitionTooLarge,
)
from fastapi import HTTPException

from lib.config import FEATURES_BUCKET, FEATURES_COLLECTION
from lib.testing import SHARED_TEST_FEATURES_DIR
from tests.fixtures import make_feature_data

STATIC_ROADS = "static-test-blue-mtn-osm-roads"
STATIC_WATER = "static-test-blue-mtn-osm-water"


# Helpers


def _load_static_template(static_name: str) -> dict:
    path = SHARED_TEST_FEATURES_DIR / f"{static_name}.json"
    if not path.exists():
        pytest.skip(
            f"{path} not found. Run the e2e fixture generator for {static_name}."
        )
    with open(path) as f:
        return json.load(f)


def _load_static_parquet(static_name: str) -> gpd.GeoDataFrame:
    """Read the static GeoParquet blob from bucket root for cross-checking."""
    url = f"gs://{FEATURES_BUCKET}/{static_name}.parquet"
    fs = gcsfs.GCSFileSystem()
    if not fs.exists(f"{FEATURES_BUCKET}/{static_name}.parquet"):
        pytest.skip(
            f"{url} not found. Run the e2e fixture generator for {static_name}."
        )
    return gpd.read_parquet(url)


def metadata_route(domain_id: str, feature_id: str):
    return f"/domains/{domain_id}/features/{feature_id}/data/metadata"


def partition_route(domain_id: str, feature_id: str, partition_index: int):
    return f"/domains/{domain_id}/features/{feature_id}/data/{partition_index}"


def _install_static_feature(firestore_client, test_owner_id, domain_id, static_name):
    """Copy the bucket-root static blob into the test domain + register Firestore doc."""
    fs = gcsfs.GCSFileSystem()
    src = f"{FEATURES_BUCKET}/{static_name}.parquet"
    dst = f"{FEATURES_BUCKET}/{domain_id}/{static_name}.parquet"
    if not fs.exists(src):
        pytest.skip(
            f"gs://{src} not found. Run the e2e fixture generator for {static_name}."
        )
    if fs.exists(dst):
        fs.rm(dst)
    fs.cp(src, dst)

    template = _load_static_template(static_name)
    template["id"] = static_name
    template["owner_id"] = test_owner_id
    template["domain_id"] = domain_id
    doc_ref = firestore_client.collection(FEATURES_COLLECTION).document(static_name)
    doc_ref.set(template)
    return template, doc_ref, dst


def _uninstall_static_feature(doc_ref, blob_path):
    fs = gcsfs.GCSFileSystem()
    doc_ref.delete()
    if fs.exists(blob_path):
        fs.rm(blob_path)


# Fixtures


@pytest.fixture(scope="session")
def static_roads_in_firestore(firestore_client, test_owner_id, domain_for_testing):
    template, doc_ref, blob = _install_static_feature(
        firestore_client, test_owner_id, domain_for_testing["id"], STATIC_ROADS
    )
    yield template
    _uninstall_static_feature(doc_ref, blob)


@pytest.fixture(scope="session")
def static_water_in_firestore(firestore_client, test_owner_id, domain_for_testing):
    template, doc_ref, blob = _install_static_feature(
        firestore_client, test_owner_id, domain_for_testing["id"], STATIC_WATER
    )
    yield template
    _uninstall_static_feature(doc_ref, blob)


@pytest.fixture(scope="session")
def static_roads_gdf():
    """The static roads GeoParquet parsed locally for cross-check assertions."""
    return _load_static_parquet(STATIC_ROADS)


@pytest.fixture(scope="session")
def pending_feature_in_firestore(firestore_client, domain_for_testing):
    """A pending feature (not completed) for 422 validation."""
    feat = make_feature_data(
        domain_id=domain_for_testing["id"], name="Pending feature", status="pending"
    )
    doc_ref = firestore_client.collection(FEATURES_COLLECTION).document(feat["id"])
    doc_ref.set(feat)
    yield feat
    doc_ref.delete()


@pytest.fixture(scope="session")
def feature_with_different_owner(firestore_client, domain_with_different_owner):
    feat = make_feature_data(
        domain_id=domain_with_different_owner["id"],
        owner_id="different-owner",
        name="Other user's feature",
        status="completed",
    )
    doc_ref = firestore_client.collection(FEATURES_COLLECTION).document(feat["id"])
    doc_ref.set(feat)
    yield feat
    doc_ref.delete()


@pytest.fixture
def completed_feature_missing_blob(firestore_client, test_owner_id, domain_for_testing):
    """A completed feature whose GCS blob doesn't exist (fresh uuid)."""
    feat = make_feature_data(
        domain_id=domain_for_testing["id"],
        owner_id=test_owner_id,
        name="Missing-blob feature",
        status="completed",
    )
    feat["id"] = f"missing-{uuid4().hex}"
    doc_ref = firestore_client.collection(FEATURES_COLLECTION).document(feat["id"])
    doc_ref.set(feat)
    yield feat
    doc_ref.delete()


# /data/metadata tests


class TestGetFeatureDataMetadata:
    """GET /domains/{domain_id}/features/{feature_id}/data/metadata."""

    def test_returns_200_with_partition_layout(
        self,
        client,
        domain_for_testing,
        static_roads_in_firestore,
        static_roads_gdf,
    ):
        response = client.get(metadata_route(domain_for_testing["id"], STATIC_ROADS))
        assert response.status_code == 200, response.text

        body = response.json()
        n = len(static_roads_gdf)
        expected_partitions = (
            n + features_cache.PARTITION_SIZE - 1
        ) // features_cache.PARTITION_SIZE

        assert body["total_features"] == n
        assert body["partition_size"] == features_cache.PARTITION_SIZE
        assert body["partition_count"] == expected_partitions

    def test_water_metadata_returns_200(
        self, client, domain_for_testing, static_water_in_firestore
    ):
        response = client.get(metadata_route(domain_for_testing["id"], STATIC_WATER))
        assert response.status_code == 200, response.text
        body = response.json()
        assert body["total_features"] >= 0
        assert body["partition_size"] == features_cache.PARTITION_SIZE
        assert body["partition_count"] >= 0

    def test_unknown_feature_returns_404(self, client, domain_for_testing):
        response = client.get(
            metadata_route(domain_for_testing["id"], "00000000000000000000000000000000")
        )
        assert response.status_code == 404

    def test_feature_owned_by_other_user_returns_404(
        self, client, domain_for_testing, feature_with_different_owner
    ):
        response = client.get(
            metadata_route(domain_for_testing["id"], feature_with_different_owner["id"])
        )
        assert response.status_code == 404

    def test_pending_feature_returns_422(
        self, client, domain_for_testing, pending_feature_in_firestore
    ):
        response = client.get(
            metadata_route(domain_for_testing["id"], pending_feature_in_firestore["id"])
        )
        assert response.status_code == 422

    def test_completed_feature_with_missing_blob_returns_422(
        self, client, domain_for_testing, completed_feature_missing_blob
    ):
        response = client.get(
            metadata_route(
                domain_for_testing["id"], completed_feature_missing_blob["id"]
            )
        )
        assert response.status_code == 422
        assert "not found in storage" in response.json()["detail"].lower()


# /data/{partition_index} tests


class TestGetFeatureDataPartition:
    """GET /domains/{domain_id}/features/{feature_id}/data/{partition_index}."""

    def test_returns_200_geojson_for_partition_zero(
        self,
        client,
        domain_for_testing,
        static_roads_in_firestore,
        static_roads_gdf,
    ):
        response = client.get(
            partition_route(domain_for_testing["id"], STATIC_ROADS, 0)
        )
        assert response.status_code == 200, response.text
        assert response.headers["content-type"].startswith("application/geo+json")

        body = response.json()
        assert body["type"] == "FeatureCollection"

        n = len(static_roads_gdf)
        expected_first_size = min(features_cache.PARTITION_SIZE, n)
        assert len(body["features"]) == expected_first_size

    def test_iterating_partitions_reproduces_source(
        self,
        client,
        domain_for_testing,
        static_roads_in_firestore,
        static_roads_gdf,
    ):
        """Round-trip: concatenating every partition reproduces the source
        GeoDataFrame feature-by-feature.

        Compares against ``static_roads_gdf.to_json()`` — the same serialization
        the server runs in ``cache._row_group_to_geojson_bytes`` would produce
        on the full source — so per-feature equality is exact.
        """
        meta = client.get(metadata_route(domain_for_testing["id"], STATIC_ROADS)).json()
        partition_count = meta["partition_count"]

        collected = []
        for idx in range(partition_count):
            response = client.get(
                partition_route(domain_for_testing["id"], STATIC_ROADS, idx)
            )
            assert response.status_code == 200, response.text
            body = response.json()
            assert body["type"] == "FeatureCollection"
            collected.extend(body["features"])

        expected = json.loads(static_roads_gdf.to_json())["features"]

        assert len(collected) == len(expected)
        # Per-feature equality in source order. Compare via canonical JSON so
        # dict-key ordering differences (which are semantically irrelevant)
        # don't trigger spurious mismatches.
        for i, (got, want) in enumerate(zip(collected, expected)):
            assert json.dumps(got, sort_keys=True) == json.dumps(
                want, sort_keys=True
            ), f"feature {i} mismatch:\n got={got}\nwant={want}"

    def test_water_endpoint_returns_geojson(
        self, client, domain_for_testing, static_water_in_firestore
    ):
        """Smoke-test water alongside roads. Blue Mtn may genuinely have
        zero water features; in that case partition_count is 0 and
        /data/{partition_index} is intentionally a 422 for every index."""
        meta = client.get(metadata_route(domain_for_testing["id"], STATIC_WATER)).json()
        if meta["partition_count"] == 0:
            pytest.skip("water fixture has zero features; no partitions to fetch")
        response = client.get(
            partition_route(domain_for_testing["id"], STATIC_WATER, 0)
        )
        assert response.status_code == 200, response.text
        body = response.json()
        assert body["type"] == "FeatureCollection"

    def test_partition_out_of_range_returns_422(
        self, client, domain_for_testing, static_roads_in_firestore
    ):
        response = client.get(
            partition_route(domain_for_testing["id"], STATIC_ROADS, 99999)
        )
        assert response.status_code == 422
        assert "out of range" in response.json()["detail"].lower()

    def test_negative_partition_returns_422(
        self, client, domain_for_testing, static_roads_in_firestore
    ):
        # FastAPI's Path(ge=0) catches this before the cache layer.
        response = client.get(
            partition_route(domain_for_testing["id"], STATIC_ROADS, -1)
        )
        assert response.status_code == 422

    def test_unknown_feature_returns_404(self, client, domain_for_testing):
        response = client.get(
            partition_route(
                domain_for_testing["id"], "00000000000000000000000000000000", 0
            )
        )
        assert response.status_code == 404

    def test_feature_owned_by_other_user_returns_404(
        self, client, domain_for_testing, feature_with_different_owner
    ):
        response = client.get(
            partition_route(
                domain_for_testing["id"], feature_with_different_owner["id"], 0
            )
        )
        assert response.status_code == 404

    def test_pending_feature_returns_422(
        self, client, domain_for_testing, pending_feature_in_firestore
    ):
        response = client.get(
            partition_route(
                domain_for_testing["id"], pending_feature_in_firestore["id"], 0
            )
        )
        assert response.status_code == 422

    def test_completed_feature_with_missing_blob_returns_422(
        self, client, domain_for_testing, completed_feature_missing_blob
    ):
        response = client.get(
            partition_route(
                domain_for_testing["id"], completed_feature_missing_blob["id"], 0
            )
        )
        assert response.status_code == 422
        assert "not found in storage" in response.json()["detail"].lower()

    @pytest.mark.asyncio
    async def test_malformed_parquet_returns_422(self, monkeypatch):
        """Direct-call test: a monkeypatched cache that raises
        InvalidFeatureParquet maps to a 422 with an explanatory detail.
        In-process — monkeypatch can't cross the live-server boundary."""

        async def _ok_doc(*args, **kwargs):
            return None, SimpleNamespace(
                to_dict=lambda: {
                    "id": "feat-x",
                    "domain_id": "dom-1",
                    "status": "completed",
                }
            )

        async def _broken(domain_id, feature_id, partition_index):
            raise InvalidFeatureParquet("simulated malformed parquet")

        monkeypatch.setattr(features_router, "get_document_async", _ok_doc)
        monkeypatch.setattr(features_router, "fetch_partition_geojson", _broken)

        with pytest.raises(HTTPException) as exc:
            await features_router.get_feature_data_partition(
                request=SimpleNamespace(state=SimpleNamespace(id="owner-1")),
                domain={"id": "dom-1"},
                feature_id="feat-x",
                partition_index=0,
            )
        assert exc.value.status_code == 422
        assert "malformed" in exc.value.detail.lower()

    @pytest.mark.asyncio
    async def test_413_when_partition_exceeds_size_cap(self, monkeypatch):
        """Direct-call test: PartitionTooLarge maps to 413."""

        async def _ok_doc(*args, **kwargs):
            return None, SimpleNamespace(
                to_dict=lambda: {
                    "id": "feat-x",
                    "domain_id": "dom-1",
                    "status": "completed",
                }
            )

        async def _too_large(domain_id, feature_id, partition_index):
            raise PartitionTooLarge(50_000_000, features_cache.MAX_RESPONSE_BYTES)

        monkeypatch.setattr(features_router, "get_document_async", _ok_doc)
        monkeypatch.setattr(features_router, "fetch_partition_geojson", _too_large)

        with pytest.raises(HTTPException) as exc:
            await features_router.get_feature_data_partition(
                request=SimpleNamespace(state=SimpleNamespace(id="owner-1")),
                domain={"id": "dom-1"},
                feature_id="feat-x",
                partition_index=0,
            )
        assert exc.value.status_code == 413
        assert "re-create" in exc.value.detail.lower()
